---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://opendev.org/openstack/requirements
requirements_git_install_branch: e1b6d44475791140aa6717155089aaecace36c68 # HEAD as of 25.08.2019
requirements_git_track_branch: stable/queens


## Aodh service
aodh_git_repo: https://opendev.org/openstack/aodh
aodh_git_install_branch: fce6e7b430c4732425e2ab41ec2bd231abda4840  # HEAD as of 25.08.2019
aodh_git_project_group: aodh_all
aodh_git_track_branch: stable/queens


## Barbican service
barbican_git_repo: https://opendev.org/openstack/barbican
barbican_git_install_branch: 9436e5a2e2cb8e9e858eee2c9ecf9d5299b5faf2  # HEAD as of 25.08.2019
barbican_git_project_group: barbican_all
barbican_git_track_branch: stable/queens


## Ceilometer service
ceilometer_git_repo: https://opendev.org/openstack/ceilometer
ceilometer_git_install_branch: b4ea5fcae09fa4e6e0548f74299f19dc7017edac  # HEAD as of 25.08.2019
ceilometer_git_project_group: ceilometer_all
ceilometer_git_track_branch: stable/queens


## Cinder service
cinder_git_repo: https://opendev.org/openstack/cinder
cinder_git_install_branch: f515bdca70f6a6bb5de0afb3f4865728b389ca40  # HEAD as of 25.08.2019
cinder_git_project_group: cinder_all
cinder_git_track_branch: stable/queens


## Cloudkitty service
cloudkitty_git_repo: https://opendev.org/openstack/cloudkitty
cloudkitty_git_install_branch: 9850bd1e5dadff34fe615694232842429b187095 # HEAD of stable/queens as of 25.08.2019
cloudkitty_git_project_group: cloudkitty_all
cloudkitty_git_track_branch: stable/queens


## Designate service
designate_git_repo: https://opendev.org/openstack/designate
designate_git_install_branch: c7987ef4b74962ccdc50b5aad76b6ed973f7e70c  # HEAD as of 25.08.2019
designate_git_project_group: designate_all
designate_git_track_branch: stable/queens


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://opendev.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: ad60b7a178490d39b149ec1975a780a2b5f133a2  # HEAD as of 25.08.2019
designate_dashboard_git_project_group: horizon_all
designate_dashboard_git_track_branch: stable/queens


## Dragonflow service
dragonflow_git_repo: https://opendev.org/openstack/dragonflow
dragonflow_git_install_branch: 098ac1e77c0b3164826648f96e26319ed9bb28d2  # HEAD as of 25.08.2019
dragonflow_git_project_group: neutron_all
dragonflow_git_track_branch: stable/queens


## Glance service
glance_git_repo: https://opendev.org/openstack/glance
glance_git_install_branch: 37c7c0022c9b41c949a9f0d938e0c1ded6d41d50  # HEAD as of 25.08.2019
glance_git_project_group: glance_all
glance_git_track_branch: stable/queens


## Heat service
heat_git_repo: https://opendev.org/openstack/heat
heat_git_install_branch: ad54909f4274d90bee4455e615ec32338cad0c3a  # HEAD as of 25.08.2019
heat_git_project_group: heat_all
heat_git_track_branch: stable/queens


## Horizon service
horizon_git_repo: https://opendev.org/openstack/horizon
horizon_git_install_branch: ae1f4abd58f43911c6d8ff0490cb21ee658f6c1e  # HEAD as of 25.08.2019
horizon_git_project_group: horizon_all
horizon_git_track_branch: stable/queens

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://opendev.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: 6aa7e39514763a70fbcbe090df10a0b1b975f918  # HEAD as of 25.08.2019
ironic_dashboard_git_project_group: horizon_all
ironic_dashboard_git_track_branch: stable/queens

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://opendev.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: 94d5937dc2d602819f359e3859f0fb9f334313fb  # HEAD as of 25.08.2019
magnum_dashboard_git_project_group: horizon_all
magnum_dashboard_git_track_branch: stable/queens

## Horizon LBaaS dashboard plugin
neutron_lbaas_dashboard_git_repo: https://opendev.org/openstack/neutron-lbaas-dashboard
neutron_lbaas_dashboard_git_install_branch: ccf86210e5bbb92cddbca05b921cc370b17bc102  # HEAD as of 25.08.2019
neutron_lbaas_dashboard_git_project_group: horizon_all
neutron_lbaas_dashboard_git_track_branch: stable/queens

## Horizon FWaaS dashboard plugin
neutron_fwaas_dashboard_git_repo: https://opendev.org/openstack/neutron-fwaas-dashboard
neutron_fwaas_dashboard_git_install_branch: 1a1fa2bcfb27527341812ece2346569f3700e342  # HEAD as of 25.08.2019
neutron_fwaas_dashboard_git_project_group: horizon_all
neutron_fwaas_dashboard_git_track_branch: stable/queens

## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://opendev.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: 0fb5197b80642817761b8e68db3bbace412e357c # HEAD as of 25.08.2019
sahara_dashboard_git_project_group: horizon_all
sahara_dashboard_git_track_branch: stable/queens

## Horizon Heat dashboard
heat_dashboard_git_repo: https://opendev.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: 4b8643f475492182bf2c853004b9494638ad5c3c  # HEAD as of 25.08.2019
heat_dashboard_git_project_group: horizon_all
heat_dashboard_git_track_branch: stable/queens


## Keystone service
keystone_git_repo: https://opendev.org/openstack/keystone
keystone_git_install_branch: 71f45f12cb625a3b0cab41cffc1623bcdd86f05e  # HEAD as of 25.08.2019
keystone_git_project_group: keystone_all
keystone_git_track_branch: stable/queens


## Neutron service
neutron_git_repo: https://opendev.org/openstack/neutron
neutron_git_install_branch: fb82e454bb8ed34d5d22aa807270f5275feba470  # HEAD as of 25.08.2019
neutron_git_project_group: neutron_all
neutron_git_track_branch: stable/queens

neutron_lbaas_git_repo: https://opendev.org/openstack/neutron-lbaas
neutron_lbaas_git_install_branch: b86fcef0115f79b4685b2e5029daebdb41815352  # HEAD as of 25.08.2019
neutron_lbaas_git_project_group: neutron_all
neutron_lbaas_git_track_branch: stable/queens

neutron_vpnaas_git_repo: https://opendev.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: e97a9f1368ecd011c6111f0b835d62aa70fefe51  # HEAD as of 25.08.2019
neutron_vpnaas_git_project_group: neutron_all
neutron_vpnaas_git_track_branch: stable/queens

neutron_fwaas_git_repo: https://opendev.org/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: 06d051f65ebebaa71b7ed22bb7ce1a4cf2f84d84  # HEAD as of 25.08.2019
neutron_fwaas_git_project_group: neutron_all
neutron_fwaas_git_track_branch: stable/queens

neutron_dynamic_routing_git_repo: https://opendev.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: acdef8ed195d0d4f4326cb0a0d85bbe12c7b0506  # HEAD as of 25.08.2019
neutron_dynamic_routing_git_project_group: neutron_all
neutron_dynamic_routing_git_track_branch: stable/queens

networking_calico_git_repo: https://opendev.org/openstack/networking-calico
networking_calico_git_install_branch: 79bdf4995d102833d23479180350216fc59e4b94  # HEAD as of 25.08.2019
networking_calico_git_project_group: neutron_all
networking_calico_git_track_branch: master

networking_odl_git_repo: https://opendev.org/openstack/networking-odl
networking_odl_git_install_branch: 692dd5fc143e2a63b993ac8992706b20f97e54a3  # HEAD as of 25.08.2019
networking_odl_git_project_group: neutron_all
networking_odl_git_track_branch: stable/queens

networking_bgpvpn_git_repo: https://opendev.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: 987d2fb601571d6773d39a6e8ed050b09306950b  # HEAD as of 25.08.2019
networking_bgpvpn_git_project_group: neutron_all
networking_bgpvpn_git_track_branch: stable/queens

networking_sfc_git_repo: https://opendev.org/openstack/networking-sfc
networking_sfc_git_install_branch: bb7dfcab75016dd7511961f2aa2d6187b6838412  # HEAD as of 25.08.2019
networking_sfc_git_project_group: neutron_all
networking_sfc_git_track_branch: stable/queens


## Nova service
nova_git_repo: https://opendev.org/openstack/nova
nova_git_install_branch: fab410ceeca43e79b1ea138805e118ed6bbe10d9  # HEAD as of 25.08.2019
nova_git_project_group: nova_all
nova_git_track_branch: stable/queens


## PowerVM Virt Driver
nova_powervm_git_repo: https://opendev.org/openstack/nova-powervm
nova_powervm_git_install_branch: e40f0e815cd8cf0ed15c8c3163cec19d2f2489f7  # HEAD as of 25.08.2019
nova_powervm_git_project_group: nova_all
nova_powervm_git_track_branch: stable/queens


## LXD Virt Driver
nova_lxd_git_repo: https://opendev.org/openstack/nova-lxd
nova_lxd_git_install_branch: a029d2af2ff2d1fc6f695e93f19e82fcc94c3f1e  # HEAD as of 25.08.2019
nova_lxd_git_project_group: nova_all
nova_lxd_git_track_branch: stable/queens


## Sahara service
sahara_git_repo: https://opendev.org/openstack/sahara
sahara_git_install_branch: 3224ba78621ded02e83e1645a4f9fdf39bebfa8a # HEAD as of 25.08.2019
sahara_git_project_group: sahara_all
sahara_git_track_branch: stable/queens


## Swift service
swift_git_repo: https://opendev.org/openstack/swift
swift_git_install_branch: 9c8b310021d8b1e373c99594d153458109a52fd2 # HEAD as of 25.08.2019
swift_git_project_group: swift_all
swift_git_track_branch: stable/queens


## Swift3 middleware
swift_swift3_git_repo: https://opendev.org/openstack/swift3
swift_swift3_git_install_branch: 90db5d1510b2a770387961e7bf0fbeae8101ba45 # FROZEN HEAD of "master" as of 27.08.2018
swift_swift3_git_project_group: swift_all
swift_swift3_git_track_branch: None


## Ironic service
ironic_git_repo: https://opendev.org/openstack/ironic
ironic_git_install_branch: fa471c680c6918e93627df334b5cbde8c591345c  # HEAD as of 25.08.2019
ironic_git_project_group: ironic_all
ironic_git_track_branch: stable/queens


## Magnum service
magnum_git_repo: https://opendev.org/openstack/magnum
magnum_git_install_branch: ee653e0fed831084dfd4a0039facf69cf5c36153  # HEAD as of 25.08.2019
magnum_git_project_group: magnum_all
magnum_git_track_branch: stable/queens


## Trove service
trove_git_repo: https://opendev.org/openstack/trove
trove_git_install_branch: 43093806314d234547e0e50fc3775e6b4e54acb5 # HEAD as of 25.08.2019
trove_git_project_group: trove_all
trove_git_track_branch: stable/queens

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://opendev.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: fd0b87bde04d52ffcfe9bd84497ce26375002b45 # HEAD as of 25.08.2019
trove_dashboard_git_project_group: horizon_all
trove_dashboard_git_track_branch: stable/queens


## Octavia service
octavia_git_repo: https://opendev.org/openstack/octavia
octavia_git_install_branch: 7eb83accd543535065c150c62219ad0567d715b2  # HEAD as of 25.08.2019
octavia_git_project_group: octavia_all
octavia_git_track_branch: stable/queens

## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://opendev.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: 51d1915049618edf56d76df9ef19ba4ecddce44b  # HEAD as of 25.08.2019
octavia_dashboard_git_project_group: horizon_all
octavia_dashboard_git_track_branch: stable/queens


## Molteniron service
molteniron_git_repo: https://opendev.org/openstack/molteniron
molteniron_git_install_branch: 094276cda77d814d07ad885e7d63de8d1243750a # FROZEN HEAD of "master" as of 27.08.2018
molteniron_git_project_group: molteniron_all
molteniron_git_track_branch: None


## Tacker service
tacker_git_repo: https://opendev.org/openstack/tacker
tacker_git_install_branch: 323c3481cc8b51b1131fd7cef02c65370a835f4e # HEAD as of 25.08.2019
tacker_git_project_group: tacker_all
tacker_git_track_branch: stable/queens


## Adjutant service
adjutant_git_repo: https://opendev.org/openstack/adjutant
adjutant_git_install_branch: 4c78d2cf6df8cf9865001d66002aa1534011f816 # HEAD of stable/queens as of 2019-11-13
adjutant_git_project_group: adjutant_all
adjutant_git_track_branch: stable/queens
