---
component_skel:
  adjutant_api:
    belongs_to:
      - adjutant_all

container_skel:
  adjutant_container:
    belongs_to:
      - adjutant-infra_containers
    contains:
      - adjutant_api
    properties:
      service_name: adjutant

physical_skel:
 adjutant-infra_containers:
   belongs_to:
     - all_containers
 adjutant-infra_hosts:
   belongs_to:
     - hosts
