---
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Stop aim on neutron nodes
  hosts: neutron_all
  serial: 1
  max_fail_percentage: 0
  gather_facts: false
  user: root
  tasks:
    - name: Stop aim services
      service:
        name: "{{ item }}"
        state: stopped
      retries: 5
      delay: 10
      with_items:
        - aim-aid
        - aim-event-service-polling
        - aim-event-service-rpc
      when:
        - "'neutron_opflex_aim_agent' in group_names"
