---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ELX NOTE: This playbook can be run with host limits to update venvs on a single node
# at a time instead of a full restart of all swift proccesses cluster wide

- name: Installation and setup of Swift
  hosts: swift_all:swift_remote_all
  gather_facts: "{{ osa_gather_facts | default(True) }}"
  user: root
  serial: 1
  vars_files:
    - "defaults/repo_packages/openstack_services.yml"
    - "defaults/{{ install_method }}_install.yml"
  pre_tasks:
    # In order to ensure that any container, software or
    # config file changes which causes a container/service
    # restart do not cause an unexpected outage, we drain
    # the load balancer back end for this container.
    - include_tasks: common-tasks/haproxy-endpoint-manage.yml
      vars:
        haproxy_backend: "{{ outer_item }}"
        haproxy_state: disabled
      with_items:
        - swift_proxy-back
        - swift_proxy_public_vip-back
      loop_control:
        loop_var: outer_item
      when: 
        - inventory_hostname in groups['swift_proxy']
        - "groups['swift_proxy'] | length > 1"

    - include_tasks: "common-tasks/os-{{ container_tech | default('lxc') }}-container-setup.yml"
      vars:
        extra_container_config_no_restart:
          - "lxc.start.order=39"
      when: not is_metal

    - include_tasks: common-tasks/unbound-clients.yml
      when:
        - hostvars['localhost']['resolvconf_enabled'] | bool

  roles:
    - role: "os_swift"
      swift_do_setup: True
      swift_do_sync: False

  post_tasks:
    # Now that container changes are done, we can set
    # the load balancer back end for this container
    # to available again.
    - include_tasks: common-tasks/haproxy-endpoint-manage.yml
      vars:
        haproxy_backend: "{{ outer_item }}"
        haproxy_state: enabled
      with_items:
        - swift_proxy-back
        - swift_proxy_public_vip-back
      loop_control:
        loop_var: outer_item
      when: 
        - inventory_hostname in groups['swift_proxy']
        - "groups['swift_proxy'] | length > 1"

  environment: "{{ deployment_environment_variables | default({}) }}"
  tags:
    - swift

- name: Installation and setup of Swift
  hosts: swift_all
  user: root
  roles:
    - role: "system_crontab_coordination"
      tags:
        - crontab
  environment: "{{ deployment_environment_variables | default({}) }}"
  tags:
    - swift
